package model;


import java.util.HashSet;
import java.util.Set;

/**
 * Bus generated by hbm2java
 */
public class Bus  implements java.io.Serializable {


     private Integer busId;
     private String busArithmosKikloforias;
     private int busArithmosTheseon;
     private String busTypebus;
     private String busXoritikotitaDematon;
     private Set busdrivers = new HashSet(0);
     private Set dromologios = new HashSet(0);

    public Bus() {
    }

	
    public Bus(String busArithmosKikloforias, int busArithmosTheseon, String busTypebus, String busXoritikotitaDematon) {
        this.busArithmosKikloforias = busArithmosKikloforias;
        this.busArithmosTheseon = busArithmosTheseon;
        this.busTypebus = busTypebus;
        this.busXoritikotitaDematon = busXoritikotitaDematon;
    }
    public Bus(String busArithmosKikloforias, int busArithmosTheseon, String busTypebus, String busXoritikotitaDematon, Set busdrivers, Set dromologios) {
       this.busArithmosKikloforias = busArithmosKikloforias;
       this.busArithmosTheseon = busArithmosTheseon;
       this.busTypebus = busTypebus;
       this.busXoritikotitaDematon = busXoritikotitaDematon;
       this.busdrivers = busdrivers;
       this.dromologios = dromologios;
    }
   
    public Integer getBusId() {
        return this.busId;
    }
    
    public void setBusId(Integer busId) {
        this.busId = busId;
    }
    public String getBusArithmosKikloforias() {
        return this.busArithmosKikloforias;
    }
    
    public void setBusArithmosKikloforias(String busArithmosKikloforias) {
        this.busArithmosKikloforias = busArithmosKikloforias;
    }
    public int getBusArithmosTheseon() {
        return this.busArithmosTheseon;
    }
    
    public void setBusArithmosTheseon(int busArithmosTheseon) {
        this.busArithmosTheseon = busArithmosTheseon;
    }
    public String getBusTypebus() {
        return this.busTypebus;
    }
    
    public void setBusTypebus(String busTypebus) {
        this.busTypebus = busTypebus;
    }
    public String getBusXoritikotitaDematon() {
        return this.busXoritikotitaDematon;
    }
    
    public void setBusXoritikotitaDematon(String busXoritikotitaDematon) {
        this.busXoritikotitaDematon = busXoritikotitaDematon;
    }
    public Set getBusdrivers() {
        return this.busdrivers;
    }
    
    public void setBusdrivers(Set busdrivers) {
        this.busdrivers = busdrivers;
    }
    public Set getDromologios() {
        return this.dromologios;
    }
    
    public void setDromologios(Set dromologios) {
        this.dromologios = dromologios;
    }




}


