package model;



/**
 * Busdriver generated by hbm2java
 */
public class Busdriver  implements java.io.Serializable {


     private BusdriverId id;
     private Bus bus;
     private String busdriverLastname;
     private String busdriverFirstname;
     private String busdriverAdt;
     private int busdriverAfm;
     private String busdriverArithmosDiplomatos;
     private String busdriverPhone;
     private String busdriverAddress;

    public Busdriver() {
    }

    public Busdriver(BusdriverId id, Bus bus, String busdriverLastname, String busdriverFirstname, String busdriverAdt, int busdriverAfm, String busdriverArithmosDiplomatos, String busdriverPhone, String busdriverAddress) {
       this.id = id;
       this.bus = bus;
       this.busdriverLastname = busdriverLastname;
       this.busdriverFirstname = busdriverFirstname;
       this.busdriverAdt = busdriverAdt;
       this.busdriverAfm = busdriverAfm;
       this.busdriverArithmosDiplomatos = busdriverArithmosDiplomatos;
       this.busdriverPhone = busdriverPhone;
       this.busdriverAddress = busdriverAddress;
    }
   
    public BusdriverId getId() {
        return this.id;
    }
    
    public void setId(BusdriverId id) {
        this.id = id;
    }
    public Bus getBus() {
        return this.bus;
    }
    
    public void setBus(Bus bus) {
        this.bus = bus;
    }
    public String getBusdriverLastname() {
        return this.busdriverLastname;
    }
    
    public void setBusdriverLastname(String busdriverLastname) {
        this.busdriverLastname = busdriverLastname;
    }
    public String getBusdriverFirstname() {
        return this.busdriverFirstname;
    }
    
    public void setBusdriverFirstname(String busdriverFirstname) {
        this.busdriverFirstname = busdriverFirstname;
    }
    public String getBusdriverAdt() {
        return this.busdriverAdt;
    }
    
    public void setBusdriverAdt(String busdriverAdt) {
        this.busdriverAdt = busdriverAdt;
    }
    public int getBusdriverAfm() {
        return this.busdriverAfm;
    }
    
    public void setBusdriverAfm(int busdriverAfm) {
        this.busdriverAfm = busdriverAfm;
    }
    public String getBusdriverArithmosDiplomatos() {
        return this.busdriverArithmosDiplomatos;
    }
    
    public void setBusdriverArithmosDiplomatos(String busdriverArithmosDiplomatos) {
        this.busdriverArithmosDiplomatos = busdriverArithmosDiplomatos;
    }
    public String getBusdriverPhone() {
        return this.busdriverPhone;
    }
    
    public void setBusdriverPhone(String busdriverPhone) {
        this.busdriverPhone = busdriverPhone;
    }
    public String getBusdriverAddress() {
        return this.busdriverAddress;
    }
    
    public void setBusdriverAddress(String busdriverAddress) {
        this.busdriverAddress = busdriverAddress;
    }




}


