package model;


import java.util.HashSet;
import java.util.Set;

/**
 * City generated by hbm2java
 */
public class City  implements java.io.Serializable {


     private Integer cityId;
     private String cityName;
     private Set dromologiosForCityIdAnaxorisi = new HashSet(0);
     private Set dromologiosForCityIdAfiksi = new HashSet(0);

    public City() {
    }

	
    public City(String cityName) {
        this.cityName = cityName;
    }
    public City(String cityName, Set dromologiosForCityIdAnaxorisi, Set dromologiosForCityIdAfiksi) {
       this.cityName = cityName;
       this.dromologiosForCityIdAnaxorisi = dromologiosForCityIdAnaxorisi;
       this.dromologiosForCityIdAfiksi = dromologiosForCityIdAfiksi;
    }
   
    public Integer getCityId() {
        return this.cityId;
    }
    
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }
    public String getCityName() {
        return this.cityName;
    }
    
    public void setCityName(String cityName) {
        this.cityName = cityName;
    }
    public Set getDromologiosForCityIdAnaxorisi() {
        return this.dromologiosForCityIdAnaxorisi;
    }
    
    public void setDromologiosForCityIdAnaxorisi(Set dromologiosForCityIdAnaxorisi) {
        this.dromologiosForCityIdAnaxorisi = dromologiosForCityIdAnaxorisi;
    }
    public Set getDromologiosForCityIdAfiksi() {
        return this.dromologiosForCityIdAfiksi;
    }
    
    public void setDromologiosForCityIdAfiksi(Set dromologiosForCityIdAfiksi) {
        this.dromologiosForCityIdAfiksi = dromologiosForCityIdAfiksi;
    }




}


