package model;


import java.util.HashSet;
import java.util.Set;

/**
 * City generated by hbm2java
 */
public class City  implements java.io.Serializable {


     private Integer cityId;
     private String cityName;
     private Set dromologiosForCityCityIdAnaxorisi = new HashSet(0);
     private Set dromologiosForCityCityIdAfiksi = new HashSet(0);

    public City() {
    }

	
    public City(String cityName) {
        this.cityName = cityName;
    }
    public City(String cityName, Set dromologiosForCityCityIdAnaxorisi, Set dromologiosForCityCityIdAfiksi) {
       this.cityName = cityName;
       this.dromologiosForCityCityIdAnaxorisi = dromologiosForCityCityIdAnaxorisi;
       this.dromologiosForCityCityIdAfiksi = dromologiosForCityCityIdAfiksi;
    }
   
    public Integer getCityId() {
        return this.cityId;
    }
    
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }
    public String getCityName() {
        return this.cityName;
    }
    
    public void setCityName(String cityName) {
        this.cityName = cityName;
    }
    public Set getDromologiosForCityCityIdAnaxorisi() {
        return this.dromologiosForCityCityIdAnaxorisi;
    }
    
    public void setDromologiosForCityCityIdAnaxorisi(Set dromologiosForCityCityIdAnaxorisi) {
        this.dromologiosForCityCityIdAnaxorisi = dromologiosForCityCityIdAnaxorisi;
    }
    public Set getDromologiosForCityCityIdAfiksi() {
        return this.dromologiosForCityCityIdAfiksi;
    }
    
    public void setDromologiosForCityCityIdAfiksi(Set dromologiosForCityCityIdAfiksi) {
        this.dromologiosForCityCityIdAfiksi = dromologiosForCityCityIdAfiksi;
    }




}


