package model;



/**
 * DemaId generated by hbm2java
 */
public class DemaId  implements java.io.Serializable {


     private int demaId;
     private int dromologioDromologioId;
     private int dromologioCityCityIdAnaxorisi;
     private int dromologioCityCityIdAfiksi;
     private int dromologioBusBusId;

    public DemaId() {
    }

    public DemaId(int demaId, int dromologioDromologioId, int dromologioCityCityIdAnaxorisi, int dromologioCityCityIdAfiksi, int dromologioBusBusId) {
       this.demaId = demaId;
       this.dromologioDromologioId = dromologioDromologioId;
       this.dromologioCityCityIdAnaxorisi = dromologioCityCityIdAnaxorisi;
       this.dromologioCityCityIdAfiksi = dromologioCityCityIdAfiksi;
       this.dromologioBusBusId = dromologioBusBusId;
    }
   
    public int getDemaId() {
        return this.demaId;
    }
    
    public void setDemaId(int demaId) {
        this.demaId = demaId;
    }
    public int getDromologioDromologioId() {
        return this.dromologioDromologioId;
    }
    
    public void setDromologioDromologioId(int dromologioDromologioId) {
        this.dromologioDromologioId = dromologioDromologioId;
    }
    public int getDromologioCityCityIdAnaxorisi() {
        return this.dromologioCityCityIdAnaxorisi;
    }
    
    public void setDromologioCityCityIdAnaxorisi(int dromologioCityCityIdAnaxorisi) {
        this.dromologioCityCityIdAnaxorisi = dromologioCityCityIdAnaxorisi;
    }
    public int getDromologioCityCityIdAfiksi() {
        return this.dromologioCityCityIdAfiksi;
    }
    
    public void setDromologioCityCityIdAfiksi(int dromologioCityCityIdAfiksi) {
        this.dromologioCityCityIdAfiksi = dromologioCityCityIdAfiksi;
    }
    public int getDromologioBusBusId() {
        return this.dromologioBusBusId;
    }
    
    public void setDromologioBusBusId(int dromologioBusBusId) {
        this.dromologioBusBusId = dromologioBusBusId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DemaId) ) return false;
		 DemaId castOther = ( DemaId ) other; 
         
		 return (this.getDemaId()==castOther.getDemaId())
 && (this.getDromologioDromologioId()==castOther.getDromologioDromologioId())
 && (this.getDromologioCityCityIdAnaxorisi()==castOther.getDromologioCityCityIdAnaxorisi())
 && (this.getDromologioCityCityIdAfiksi()==castOther.getDromologioCityCityIdAfiksi())
 && (this.getDromologioBusBusId()==castOther.getDromologioBusBusId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getDemaId();
         result = 37 * result + this.getDromologioDromologioId();
         result = 37 * result + this.getDromologioCityCityIdAnaxorisi();
         result = 37 * result + this.getDromologioCityCityIdAfiksi();
         result = 37 * result + this.getDromologioBusBusId();
         return result;
   }   


}


