package model;


import java.util.Date;

/**
 * Dema generated by hbm2java
 */
public class Dema  implements java.io.Serializable {


     private Integer demaId;
     private Dromologio dromologio;
     private Date demaDateApostoli;
     private String demaLastnameApostolea;
     private String demaFirstnameApostolea;
     private String demaLastnameParalipti;
     private String demaFirstnameParalipti;
     private int demaTemaxia;
     private String demaBaros;
     private String demaPrice;

    public Dema() {
    }

    public Dema(Dromologio dromologio, Date demaDateApostoli, String demaLastnameApostolea, String demaFirstnameApostolea, String demaLastnameParalipti, String demaFirstnameParalipti, int demaTemaxia, String demaBaros, String demaPrice) {
       this.dromologio = dromologio;
       this.demaDateApostoli = demaDateApostoli;
       this.demaLastnameApostolea = demaLastnameApostolea;
       this.demaFirstnameApostolea = demaFirstnameApostolea;
       this.demaLastnameParalipti = demaLastnameParalipti;
       this.demaFirstnameParalipti = demaFirstnameParalipti;
       this.demaTemaxia = demaTemaxia;
       this.demaBaros = demaBaros;
       this.demaPrice = demaPrice;
    }
   
    public Integer getDemaId() {
        return this.demaId;
    }
    
    public void setDemaId(Integer demaId) {
        this.demaId = demaId;
    }
    public Dromologio getDromologio() {
        return this.dromologio;
    }
    
    public void setDromologio(Dromologio dromologio) {
        this.dromologio = dromologio;
    }
    public Date getDemaDateApostoli() {
        return this.demaDateApostoli;
    }
    
    public void setDemaDateApostoli(Date demaDateApostoli) {
        this.demaDateApostoli = demaDateApostoli;
    }
    public String getDemaLastnameApostolea() {
        return this.demaLastnameApostolea;
    }
    
    public void setDemaLastnameApostolea(String demaLastnameApostolea) {
        this.demaLastnameApostolea = demaLastnameApostolea;
    }
    public String getDemaFirstnameApostolea() {
        return this.demaFirstnameApostolea;
    }
    
    public void setDemaFirstnameApostolea(String demaFirstnameApostolea) {
        this.demaFirstnameApostolea = demaFirstnameApostolea;
    }
    public String getDemaLastnameParalipti() {
        return this.demaLastnameParalipti;
    }
    
    public void setDemaLastnameParalipti(String demaLastnameParalipti) {
        this.demaLastnameParalipti = demaLastnameParalipti;
    }
    public String getDemaFirstnameParalipti() {
        return this.demaFirstnameParalipti;
    }
    
    public void setDemaFirstnameParalipti(String demaFirstnameParalipti) {
        this.demaFirstnameParalipti = demaFirstnameParalipti;
    }
    public int getDemaTemaxia() {
        return this.demaTemaxia;
    }
    
    public void setDemaTemaxia(int demaTemaxia) {
        this.demaTemaxia = demaTemaxia;
    }
    public String getDemaBaros() {
        return this.demaBaros;
    }
    
    public void setDemaBaros(String demaBaros) {
        this.demaBaros = demaBaros;
    }
    public String getDemaPrice() {
        return this.demaPrice;
    }
    
    public void setDemaPrice(String demaPrice) {
        this.demaPrice = demaPrice;
    }




}


