package model;


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Dromologio generated by hbm2java
 */
public class Dromologio  implements java.io.Serializable {


     private DromologioId id;
     private Bus bus;
     private City cityByCityCityIdAnaxorisi;
     private City cityByCityCityIdAfiksi;
     private Date dromologioDate;
     private Date dromologioTimeAnaxorisi;
     private Date dromologioTimeAfiksi;
     private String dromologioTypeDromologio;
     private String dromologioPrice;
     private Set tickets = new HashSet(0);
     private Set demas = new HashSet(0);

    public Dromologio() {
    }

	
    public Dromologio(DromologioId id, Bus bus, City cityByCityCityIdAnaxorisi, City cityByCityCityIdAfiksi, Date dromologioDate, Date dromologioTimeAnaxorisi, Date dromologioTimeAfiksi, String dromologioTypeDromologio, String dromologioPrice) {
        this.id = id;
        this.bus = bus;
        this.cityByCityCityIdAnaxorisi = cityByCityCityIdAnaxorisi;
        this.cityByCityCityIdAfiksi = cityByCityCityIdAfiksi;
        this.dromologioDate = dromologioDate;
        this.dromologioTimeAnaxorisi = dromologioTimeAnaxorisi;
        this.dromologioTimeAfiksi = dromologioTimeAfiksi;
        this.dromologioTypeDromologio = dromologioTypeDromologio;
        this.dromologioPrice = dromologioPrice;
    }
    public Dromologio(DromologioId id, Bus bus, City cityByCityCityIdAnaxorisi, City cityByCityCityIdAfiksi, Date dromologioDate, Date dromologioTimeAnaxorisi, Date dromologioTimeAfiksi, String dromologioTypeDromologio, String dromologioPrice, Set tickets, Set demas) {
       this.id = id;
       this.bus = bus;
       this.cityByCityCityIdAnaxorisi = cityByCityCityIdAnaxorisi;
       this.cityByCityCityIdAfiksi = cityByCityCityIdAfiksi;
       this.dromologioDate = dromologioDate;
       this.dromologioTimeAnaxorisi = dromologioTimeAnaxorisi;
       this.dromologioTimeAfiksi = dromologioTimeAfiksi;
       this.dromologioTypeDromologio = dromologioTypeDromologio;
       this.dromologioPrice = dromologioPrice;
       this.tickets = tickets;
       this.demas = demas;
    }
   
    public DromologioId getId() {
        return this.id;
    }
    
    public void setId(DromologioId id) {
        this.id = id;
    }
    public Bus getBus() {
        return this.bus;
    }
    
    public void setBus(Bus bus) {
        this.bus = bus;
    }
    public City getCityByCityCityIdAnaxorisi() {
        return this.cityByCityCityIdAnaxorisi;
    }
    
    public void setCityByCityCityIdAnaxorisi(City cityByCityCityIdAnaxorisi) {
        this.cityByCityCityIdAnaxorisi = cityByCityCityIdAnaxorisi;
    }
    public City getCityByCityCityIdAfiksi() {
        return this.cityByCityCityIdAfiksi;
    }
    
    public void setCityByCityCityIdAfiksi(City cityByCityCityIdAfiksi) {
        this.cityByCityCityIdAfiksi = cityByCityCityIdAfiksi;
    }
    public Date getDromologioDate() {
        return this.dromologioDate;
    }
    
    public void setDromologioDate(Date dromologioDate) {
        this.dromologioDate = dromologioDate;
    }
    public Date getDromologioTimeAnaxorisi() {
        return this.dromologioTimeAnaxorisi;
    }
    
    public void setDromologioTimeAnaxorisi(Date dromologioTimeAnaxorisi) {
        this.dromologioTimeAnaxorisi = dromologioTimeAnaxorisi;
    }
    public Date getDromologioTimeAfiksi() {
        return this.dromologioTimeAfiksi;
    }
    
    public void setDromologioTimeAfiksi(Date dromologioTimeAfiksi) {
        this.dromologioTimeAfiksi = dromologioTimeAfiksi;
    }
    public String getDromologioTypeDromologio() {
        return this.dromologioTypeDromologio;
    }
    
    public void setDromologioTypeDromologio(String dromologioTypeDromologio) {
        this.dromologioTypeDromologio = dromologioTypeDromologio;
    }
    public String getDromologioPrice() {
        return this.dromologioPrice;
    }
    
    public void setDromologioPrice(String dromologioPrice) {
        this.dromologioPrice = dromologioPrice;
    }
    public Set getTickets() {
        return this.tickets;
    }
    
    public void setTickets(Set tickets) {
        this.tickets = tickets;
    }
    public Set getDemas() {
        return this.demas;
    }
    
    public void setDemas(Set demas) {
        this.demas = demas;
    }




}


