package model;



/**
 * Euser generated by hbm2java
 */
public class Euser  implements java.io.Serializable {


     private Integer euserId;
     private String euserUsername;
     private String euserPassword;
     private String euserEmail;

    public Euser() {
    }

    public Euser(String euserUsername, String euserPassword, String euserEmail) {
       this.euserUsername = euserUsername;
       this.euserPassword = euserPassword;
       this.euserEmail = euserEmail;
    }
   
    public Integer getEuserId() {
        return this.euserId;
    }
    
    public void setEuserId(Integer euserId) {
        this.euserId = euserId;
    }
    public String getEuserUsername() {
        return this.euserUsername;
    }
    
    public void setEuserUsername(String euserUsername) {
        this.euserUsername = euserUsername;
    }
    public String getEuserPassword() {
        return this.euserPassword;
    }
    
    public void setEuserPassword(String euserPassword) {
        this.euserPassword = euserPassword;
    }
    public String getEuserEmail() {
        return this.euserEmail;
    }
    
    public void setEuserEmail(String euserEmail) {
        this.euserEmail = euserEmail;
    }




}


