package model;


import java.util.Date;

/**
 * Ticket generated by hbm2java
 */
public class Ticket  implements java.io.Serializable {


     private TicketId id;
     private Dromologio dromologio;
     private String ticketType;
     private String ticketTypeEkptosi;
     private Date ticketDateEkdosi;
     private String ticketCategoryEkdosis;
     private String ticketPrice;

    public Ticket() {
    }

    public Ticket(TicketId id, Dromologio dromologio, String ticketType, String ticketTypeEkptosi, Date ticketDateEkdosi, String ticketCategoryEkdosis, String ticketPrice) {
       this.id = id;
       this.dromologio = dromologio;
       this.ticketType = ticketType;
       this.ticketTypeEkptosi = ticketTypeEkptosi;
       this.ticketDateEkdosi = ticketDateEkdosi;
       this.ticketCategoryEkdosis = ticketCategoryEkdosis;
       this.ticketPrice = ticketPrice;
    }
   
    public TicketId getId() {
        return this.id;
    }
    
    public void setId(TicketId id) {
        this.id = id;
    }
    public Dromologio getDromologio() {
        return this.dromologio;
    }
    
    public void setDromologio(Dromologio dromologio) {
        this.dromologio = dromologio;
    }
    public String getTicketType() {
        return this.ticketType;
    }
    
    public void setTicketType(String ticketType) {
        this.ticketType = ticketType;
    }
    public String getTicketTypeEkptosi() {
        return this.ticketTypeEkptosi;
    }
    
    public void setTicketTypeEkptosi(String ticketTypeEkptosi) {
        this.ticketTypeEkptosi = ticketTypeEkptosi;
    }
    public Date getTicketDateEkdosi() {
        return this.ticketDateEkdosi;
    }
    
    public void setTicketDateEkdosi(Date ticketDateEkdosi) {
        this.ticketDateEkdosi = ticketDateEkdosi;
    }
    public String getTicketCategoryEkdosis() {
        return this.ticketCategoryEkdosis;
    }
    
    public void setTicketCategoryEkdosis(String ticketCategoryEkdosis) {
        this.ticketCategoryEkdosis = ticketCategoryEkdosis;
    }
    public String getTicketPrice() {
        return this.ticketPrice;
    }
    
    public void setTicketPrice(String ticketPrice) {
        this.ticketPrice = ticketPrice;
    }




}


