package model;



/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private UsersId id;
     private Roles roles;
     private String userLastname;
     private String userFirstname;
     private String userAdt;
     private int userAfm;
     private String userPhone;
     private String userAddress;
     private String userEmail;
     private String userUsername;
     private String userPassword;

    public Users() {
    }

    public Users(UsersId id, Roles roles, String userLastname, String userFirstname, String userAdt, int userAfm, String userPhone, String userAddress, String userEmail, String userUsername, String userPassword) {
       this.id = id;
       this.roles = roles;
       this.userLastname = userLastname;
       this.userFirstname = userFirstname;
       this.userAdt = userAdt;
       this.userAfm = userAfm;
       this.userPhone = userPhone;
       this.userAddress = userAddress;
       this.userEmail = userEmail;
       this.userUsername = userUsername;
       this.userPassword = userPassword;
    }
   
    public UsersId getId() {
        return this.id;
    }
    
    public void setId(UsersId id) {
        this.id = id;
    }
    public Roles getRoles() {
        return this.roles;
    }
    
    public void setRoles(Roles roles) {
        this.roles = roles;
    }
    public String getUserLastname() {
        return this.userLastname;
    }
    
    public void setUserLastname(String userLastname) {
        this.userLastname = userLastname;
    }
    public String getUserFirstname() {
        return this.userFirstname;
    }
    
    public void setUserFirstname(String userFirstname) {
        this.userFirstname = userFirstname;
    }
    public String getUserAdt() {
        return this.userAdt;
    }
    
    public void setUserAdt(String userAdt) {
        this.userAdt = userAdt;
    }
    public int getUserAfm() {
        return this.userAfm;
    }
    
    public void setUserAfm(int userAfm) {
        this.userAfm = userAfm;
    }
    public String getUserPhone() {
        return this.userPhone;
    }
    
    public void setUserPhone(String userPhone) {
        this.userPhone = userPhone;
    }
    public String getUserAddress() {
        return this.userAddress;
    }
    
    public void setUserAddress(String userAddress) {
        this.userAddress = userAddress;
    }
    public String getUserEmail() {
        return this.userEmail;
    }
    
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail;
    }
    public String getUserUsername() {
        return this.userUsername;
    }
    
    public void setUserUsername(String userUsername) {
        this.userUsername = userUsername;
    }
    public String getUserPassword() {
        return this.userPassword;
    }
    
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword;
    }




}


