package model;



/**
 * UsersId generated by hbm2java
 */
public class UsersId  implements java.io.Serializable {


     private int userId;
     private int rolesRoleId;

    public UsersId() {
    }

    public UsersId(int userId, int rolesRoleId) {
       this.userId = userId;
       this.rolesRoleId = rolesRoleId;
    }
   
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }
    public int getRolesRoleId() {
        return this.rolesRoleId;
    }
    
    public void setRolesRoleId(int rolesRoleId) {
        this.rolesRoleId = rolesRoleId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UsersId) ) return false;
		 UsersId castOther = ( UsersId ) other; 
         
		 return (this.getUserId()==castOther.getUserId())
 && (this.getRolesRoleId()==castOther.getRolesRoleId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getUserId();
         result = 37 * result + this.getRolesRoleId();
         return result;
   }   


}


